services:
# 言語系--------------------------------------------------
  dev:
    container_name: develop
    restart: always
    working_dir: /src/app
    image: ghcr.io/toshibe678/develop/develop:latest
#    build:
#      context: ./
#      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 18080:80
    volumes:
      - type: bind
        source: "./golang"
        target: "/src/app/go/"
#      - ./python:/app
#      - ../scripts:/scripts
#      - ./node:/app
    tty: true
    stdin_open: true

# データベース系--------------------------------------------------
  postgres:
    container_name: dev_postgres
    restart: always
    image: postgres:13
    env_file: ./.env
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - 5432
    tty: true
    stdin_open: true

  mysql:
    container_name: dev_mysql
    restart: always
    image: mysql:8
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db_data/mysql:/var/lib/mysql
    ports:
      - 3306
    tty: true
    stdin_open: true

# キャッシュ系--------------------------------------------------
  redis:
    container_name: dev_redis
    restart: always
    image: redis:6
    volumes:
      - ./db_data/redis:/data
    ports:
      - 6379
    tty: true
    stdin_open: true

#configs:
#  my_config:
#    file: ./my_config.txt
#
#secrets:
#  server-certificate:
#    file: ./server.cert
