services:
# 言語系--------------------------------------------------
  golang:
    container_name: golang_develop
    restart: always
    working_dir: /go/src/app
    build:
      context: golang
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: "./golang"
        target: "/go/"
    tty: true
    stdin_open: true

  node:
    container_name: dev_node
    restart: always
    build:
      context: ./node
      dockerfile: Dockerfile
    env_file: ./.env
    init: true
    volumes:
      - ./node:/app
      - ../scripts:/scripts
    tty: true
    stdin_open: true

  python:
    container_name: dev_python
    restart: always
    build:
      context: ./python
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./python:/app
      - ../scripts:/scripts
    tty: true
    stdin_open: true

# データベース系--------------------------------------------------
  postgres:
    container_name: dev_postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file: ./.env
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    ports:
      - 5432
    tty: true
    stdin_open: true

  mysql:
    container_name: dev_mysql
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./db_data/mysql:/var/lib/mysql
    ports:
      - 3306
    tty: true
    stdin_open: true

# キャッシュ系--------------------------------------------------
  redis:
    container_name: dev_redis
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - ./db_data/redis:/data
    ports:
      - 6379
    tty: true
    stdin_open: true

#configs:
#  my_config:
#    file: ./my_config.txt
#
#secrets:
#  server-certificate:
#    file: ./server.cert
