services:
#  app1:
#    image: awesome/webapp
#    configs:
#      - my_config
#    secrets:
#      - server-certificate
#
#  app2:
#    image: awesome/database
#    extends:
#      service: app1
  go:
    container_name: dev_go
    restart: always
    build:
      context: ./go
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /go/src/work
    command: /bin/bash
    volumes:
      - ./go:/go/src/work
    tty: true
    stdin_open: true

  node:
    container_name: dev_node
    restart: always
    build:
      context: ./node
      dockerfile: Dockerfile
    env_file: ./.env
    init: true
    volumes:
      - ./node:/app
    tty: true
    stdin_open: true

  python:
    container_name: dev_python
    restart: always
    build:
      context: ./python
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./python:/app
    tty: true
    stdin_open: true

  postgres:
    container_name: dev_postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file: ./.env
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    ports:
      - 5432
    tty: true
    stdin_open: true

  mysql:
    container_name: dev_mysql
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
    ports:
      - 3306
    tty: true
    stdin_open: true

  redis:
    container_name: dev_redis
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - redis:/data
    ports:
      - 6379
    tty: true
    stdin_open: true

volumes:
  postgres:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
#configs:
#  my_config:
#    file: ./my_config.txt
#
#secrets:
#  server-certificate:
#    file: ./server.cert
