services:
#  app1:
#    image: awesome/webapp
#    configs:
#      - my_config
#    secrets:
#      - server-certificate
#
#  app2:
#    image: awesome/database
#    extends:
#      service: app1
  go:
    container_name: "dev_go"
    restart: always
    build:
      context: ./go
      dockerfile: Dockerfile
    env_file: ./.env
    working_dir: /go/src/work
    command: /bin/bash
    volumes:
      - ./go:/go/src/work
    tty: true
    stdin_open: true

  postgres:
    container_name: dev_postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile
      args:
        - DB_LANG=ja_JP
    env_file: ./.env
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    ports:
      - "5432:5432"


#configs:
#  my_config:
#    file: ./my_config.txt
#
#secrets:
#  server-certificate:
#    file: ./server.cert
