FROM ghcr.io/toshibe678/develop/common:latest

# DockerfileのLintツール
ARG hadolint_version=2.12.0
ENV HADOLINT_VERSION=${hadolint_version}
RUN if [ $(uname -m) = "x86_64" ]; then \
                  arch="x86_64"; \
              else \
                  arch="arm64"; \
              fi && \
    curl -L "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-${arch}" -o /usr/local/bin/hadolint && \
    chmod +x /usr/local/bin/hadolint

### AWS CLI
RUN arch=$(uname -m) && \
    if [ "$arch" != "x86_64" ]; then \
        arch="aarch64"; \
    fi && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-${arch}.zip" -o "aws-cli.zip" && \
    unzip aws-cli.zip && \
    ./aws/install && \
    rm -rf aws aws-cli.zip

# gcloud
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates gnupg && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    apt-get update && \
    apt-get install -y google-cloud-sdk \
    && rm -rf /var/lib/apt/lists/*
# gcloudの初期設定 使用レポートの無効化とアップデートチェックの無効化
RUN gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true \

# azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
